/** One-purpose, no-spend xAI catalogue attestation. Never imports into production Worker. */
export const GROK_RATE_ATTESTATION_SCHEMA = "survey-qa-grok-rate-attestation/1.0.0";
export const XAI_CATALOGUE_ORIGIN = "https://api.x.ai";
// xAI documents this as the full language-model schema. `/v1/models/{id}` is deliberately not
// used: it is the minimal model view and does not define the full long-context fields.
export const XAI_CATALOGUE_PATH = "/v1/language-models/grok-4.5";
export const XAI_CATALOGUE_URL = `${XAI_CATALOGUE_ORIGIN}${XAI_CATALOGUE_PATH}`;
export const EXACT_GROK_MODEL = "grok-4.5";
export const EXACT_XAI_OWNER = "xai";
export const MAX_CATALOGUE_BYTES = 16 * 1024;
type Json = null | boolean | number | string | Json[] | { readonly [key: string]: Json };
type JsonRecord = { readonly [key: string]: Json };
export type TokenRates = Readonly<{ inputTextTicksPerToken: number; inputTextUsdPerMtok: string; cachedInputTextTicksPerToken: number; cachedInputTextUsdPerMtok: string; inputImageTicksPerToken: number; inputImageUsdPerMtok: string; outputTextTicksPerToken: number; outputTextUsdPerMtok: string }>;
export type LongTextRates = Readonly<{ inputTextTicksPerToken: number; cachedInputTextTicksPerToken: number; outputTextTicksPerToken: number }>;
export type GrokRateAttestationReceipt = Readonly<{ schemaVersion: typeof GROK_RATE_ATTESTATION_SCHEMA; observedAt: string; request: Readonly<{ method: "GET"; origin: typeof XAI_CATALOGUE_ORIGIN; path: typeof XAI_CATALOGUE_PATH; model: typeof EXACT_GROK_MODEL }>; model: Readonly<{ id: typeof EXACT_GROK_MODEL; object: "model"; ownedBy: typeof EXACT_XAI_OWNER; created: number; fingerprint: string; version: string; aliases: readonly string[]; inputModalities: readonly string[]; outputModalities: readonly string[] }>; pricing: Readonly<{ unit: "usd-ticks-per-token"; usdTicksPerUsd: 10_000_000_000; base: TokenRates; longContext: Readonly<{ thresholdTokens: number; rawTextRates: LongTextRates | null; effectiveRates: TokenRates | null; limitation: "LONG_CONTEXT_COSTING_REQUIRED" | null }>; searchTicksPerSearch: number }> }>;
/** The generated config uses a Secrets Store binding. A plain string is never accepted here. */
export type AttestationEnv = Readonly<{ XAI_API_KEY?: Readonly<{ get(): Promise<string> }> }>;
export type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export class GrokRateAttestationError extends Error { constructor(readonly code: string, message: string) { super(`${code}: ${message}`); this.name = "GrokRateAttestationError"; } }

/** Makes exactly one fixed GET. Neither model identity nor endpoint is caller-supplied. */
export async function attestGrokRate(env: AttestationEnv, fetchImpl: FetchLike = fetch, observedAt = new Date().toISOString()): Promise<GrokRateAttestationReceipt> {
  const apiKey = await resolveSecret(env.XAI_API_KEY);
  let response: Response;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10_000);
  try { response = await fetchImpl(XAI_CATALOGUE_URL, { method: "GET", redirect: "error", signal: controller.signal, headers: { accept: "application/json", authorization: `Bearer ${apiKey}` } }); }
  catch { refuse("RATE_CATALOGUE_UNREACHABLE", "the fixed xAI model catalogue could not be reached without a redirect"); }
  finally { clearTimeout(timeout); }
  if (response.status !== 200) refuse("RATE_CATALOGUE_STATUS_INVALID", "the fixed xAI model catalogue did not return HTTP 200");
  if (response.url !== "" && response.url !== XAI_CATALOGUE_URL) refuse("RATE_CATALOGUE_REDIRECTED", "the xAI response URL differs from the fixed catalogue URL");
  const contentType = response.headers.get("content-type");
  if (contentType === null || !/^application\/json(?:\s*;|\s*$)/i.test(contentType)) refuse("RATE_CATALOGUE_CONTENT_TYPE_INVALID", "the fixed xAI catalogue response is not JSON");
  return parseGrokRateCatalogue(await boundedResponseText(response, MAX_CATALOGUE_BYTES), observedAt);
}

/** Parses already-bounded input into the only receipt shape that may be reviewed. */
export function parseGrokRateCatalogue(body: string, observedAt: string): GrokRateAttestationReceipt {
  const bodyBytes = typeof body === "string" ? new TextEncoder().encode(body).byteLength : 0;
  if (bodyBytes === 0 || bodyBytes > MAX_CATALOGUE_BYTES) refuse("RATE_CATALOGUE_BODY_INVALID", "catalogue body is empty or exceeds its fixed envelope");
  if (!isRfc3339Utc(observedAt)) refuse("RATE_CATALOGUE_TIME_INVALID", "observation time is not canonical UTC RFC3339");
  const row = asRecord(parseUniqueJson(body), "$", MODEL_KEYS);
  const id = requiredString(row, "id", "$"), object = requiredString(row, "object", "$"), ownedBy = requiredString(row, "owned_by", "$");
  if (id !== EXACT_GROK_MODEL || object !== "model" || ownedBy !== EXACT_XAI_OWNER) refuse("RATE_CATALOGUE_IDENTITY_INVALID", "catalogue model identity is not exact grok-4.5/xai/model");
  const created = requiredNonNegativeInteger(row, "created", "$"), base = tokenRates(row, "", "$"), threshold = requiredNonNegativeInteger(row, "long_context_threshold", "$"), searchTicksPerSearch = requiredNonNegativeInteger(row, "search_price", "$");
  const rawTextRates = longTextRates(row, "$"), effectiveRates = threshold === 0 ? null : effectiveLongRates(base, rawTextRates);
  if (threshold === 0 && rawTextRates !== null) refuse("RATE_CATALOGUE_LONG_CONTEXT_INVALID", "a no-tier model may not declare long-context text prices");
  const fingerprint = requiredString(row, "fingerprint", "$"), version = requiredString(row, "version", "$"), aliases = requiredUniqueStringArray(row, "aliases", "$"), inputModalities = requiredUniqueStringArray(row, "input_modalities", "$"), outputModalities = requiredUniqueStringArray(row, "output_modalities", "$");
  return Object.freeze({ schemaVersion: GROK_RATE_ATTESTATION_SCHEMA, observedAt, request: Object.freeze({ method: "GET", origin: XAI_CATALOGUE_ORIGIN, path: XAI_CATALOGUE_PATH, model: EXACT_GROK_MODEL }), model: Object.freeze({ id: EXACT_GROK_MODEL, object: "model", ownedBy: EXACT_XAI_OWNER, created, fingerprint, version, aliases: Object.freeze(aliases), inputModalities: Object.freeze(inputModalities), outputModalities: Object.freeze(outputModalities) }), pricing: Object.freeze({ unit: "usd-ticks-per-token", usdTicksPerUsd: 10_000_000_000, base, longContext: Object.freeze({ thresholdTokens: threshold, rawTextRates, effectiveRates, limitation: threshold === 0 ? null : "LONG_CONTEXT_COSTING_REQUIRED" }), searchTicksPerSearch }) });
}
/** xAI's integer price is USD ticks/token. (ticks * 1M) / 1e10 USD is rendered exactly. */
export function ticksPerTokenToUsdPerMtok(ticks: number): string { if (!Number.isSafeInteger(ticks) || ticks < 0) refuse("RATE_PRICE_INVALID", "price must be a non-negative safe integer number of ticks per token"); const scaled = BigInt(ticks) * 1_000_000n, whole = scaled / 10_000_000_000n, fraction = (scaled % 10_000_000_000n).toString().padStart(10, "0").replace(/0+$/, ""); return fraction.length === 0 ? whole.toString() : `${whole}.${fraction}`; }
const MODEL_KEYS = new Set(["id", "object", "owned_by", "created", "fingerprint", "version", "aliases", "input_modalities", "output_modalities", "prompt_text_token_price", "cached_prompt_text_token_price", "prompt_image_token_price", "completion_text_token_price", "prompt_text_token_price_long_context", "cached_prompt_text_token_price_long_context", "completion_text_token_price_long_context", "long_context_threshold", "search_price"]);
function tokenRates(row: JsonRecord, suffix: "", path: string): TokenRates { const input = requiredNonNegativeInteger(row, `prompt_text_token_price${suffix}`, path), cached = requiredNonNegativeInteger(row, `cached_prompt_text_token_price${suffix}`, path), image = requiredNonNegativeInteger(row, `prompt_image_token_price${suffix}`, path), output = requiredNonNegativeInteger(row, `completion_text_token_price${suffix}`, path); return Object.freeze({ inputTextTicksPerToken: input, inputTextUsdPerMtok: ticksPerTokenToUsdPerMtok(input), cachedInputTextTicksPerToken: cached, cachedInputTextUsdPerMtok: ticksPerTokenToUsdPerMtok(cached), inputImageTicksPerToken: image, inputImageUsdPerMtok: ticksPerTokenToUsdPerMtok(image), outputTextTicksPerToken: output, outputTextUsdPerMtok: ticksPerTokenToUsdPerMtok(output) }); }
function longTextRates(row: JsonRecord, path: string): LongTextRates | null { const keys = ["prompt_text_token_price_long_context", "cached_prompt_text_token_price_long_context", "completion_text_token_price_long_context"]; if (keys.every((key) => !(key in row))) return null; if (keys.some((key) => !(key in row))) refuse("RATE_CATALOGUE_LONG_CONTEXT_INVALID", "long-context text rate fields must appear together"); return Object.freeze({ inputTextTicksPerToken: requiredNonNegativeInteger(row, keys[0] ?? "", path), cachedInputTextTicksPerToken: requiredNonNegativeInteger(row, keys[1] ?? "", path), outputTextTicksPerToken: requiredNonNegativeInteger(row, keys[2] ?? "", path) }); }
function effectiveLongRates(base: TokenRates, raw: LongTextRates | null): TokenRates { const input = raw?.inputTextTicksPerToken || base.inputTextTicksPerToken, cached = raw?.cachedInputTextTicksPerToken || base.cachedInputTextTicksPerToken, output = raw?.outputTextTicksPerToken || base.outputTextTicksPerToken; return Object.freeze({ inputTextTicksPerToken: input, inputTextUsdPerMtok: ticksPerTokenToUsdPerMtok(input), cachedInputTextTicksPerToken: cached, cachedInputTextUsdPerMtok: ticksPerTokenToUsdPerMtok(cached), inputImageTicksPerToken: base.inputImageTicksPerToken, inputImageUsdPerMtok: base.inputImageUsdPerMtok, outputTextTicksPerToken: output, outputTextUsdPerMtok: ticksPerTokenToUsdPerMtok(output) }); }
async function resolveSecret(binding: AttestationEnv["XAI_API_KEY"]): Promise<string> { if (binding === undefined || typeof binding.get !== "function") refuse("XAI_KEY_UNAVAILABLE", "the XAI API key Secrets Store binding is unavailable"); let timeout: ReturnType<typeof setTimeout> | undefined; try { const value = await Promise.race([binding.get(), new Promise<never>((_, reject) => { timeout = setTimeout(() => reject(new Error("timeout")), 5_000); })]); if (typeof value !== "string" || value.length < 8 || value.length > 4096) refuse("XAI_KEY_UNAVAILABLE", "the XAI API key Secret Store value is unavailable"); return value; } catch (error) { if (error instanceof GrokRateAttestationError) throw error; return refuse("XAI_KEY_UNAVAILABLE", "the XAI API key Secret Store value could not be read"); } finally { if (timeout !== undefined) clearTimeout(timeout); } }
async function boundedResponseText(response: Response, maximum: number): Promise<string> { const declared = response.headers.get("content-length"); if (declared !== null && (!/^(0|[1-9][0-9]*)$/.test(declared) || Number(declared) > maximum)) refuse("RATE_CATALOGUE_BODY_INVALID", "catalogue content length is malformed or too large"); if (response.body === null) refuse("RATE_CATALOGUE_BODY_INVALID", "catalogue response has no body"); const reader = response.body.getReader(), chunks: Uint8Array[] = []; let total = 0; try { for (;;) { const next = await reader.read(); if (next.done) break; total += next.value.byteLength; if (total > maximum) refuse("RATE_CATALOGUE_BODY_INVALID", "catalogue body exceeds its fixed envelope"); chunks.push(next.value); } } finally { reader.releaseLock(); } const bytes = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } try { return new TextDecoder("utf-8", { fatal: true, ignoreBOM: false }).decode(bytes); } catch { return refuse("RATE_CATALOGUE_BODY_INVALID", "catalogue body is not valid UTF-8"); } }
function asRecord(value: Json, path: string, keys: ReadonlySet<string>): JsonRecord { if (value === null || Array.isArray(value) || typeof value !== "object") refuse("RATE_CATALOGUE_SCHEMA_INVALID", `${path} must be an object`); for (const key of Object.keys(value)) if (!keys.has(key)) refuse("RATE_CATALOGUE_SCHEMA_INVALID", `${path}.${key} is not an allowed catalogue field`); return value; }
function requiredString(row: JsonRecord, key: string, path: string): string { const value = row[key]; if (typeof value !== "string" || value.length === 0 || value.length > 256) refuse("RATE_CATALOGUE_SCHEMA_INVALID", `${path}.${key} must be a bounded string`); return value; }
function requiredUniqueStringArray(row: JsonRecord, key: string, path: string): string[] { const value = row[key]; if (!Array.isArray(value) || value.length > 16 || value.some((item) => typeof item !== "string" || item.length === 0 || item.length > 64) || new Set(value).size !== value.length) refuse("RATE_CATALOGUE_SCHEMA_INVALID", `${path}.${key} must be a bounded unique string array`); return [...value] as string[]; }
function requiredNonNegativeInteger(row: JsonRecord, key: string, path: string): number { const value = row[key]; if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0 || value > 1_000_000_000_000) refuse("RATE_CATALOGUE_PRICE_INVALID", `${path}.${key} must be a non-negative bounded integer`); return value; }
function isRfc3339Utc(value: string): boolean { return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) && Number.isFinite(Date.parse(value)); }
function refuse(code: string, message: string): never { throw new GrokRateAttestationError(code, message); }
/** Minimal JSON parser: JSON.parse silently accepts duplicate object keys, this does not. */
function parseUniqueJson(text: string): Json { let index = 0, nodes = 0; const ws = () => { while (/[\u0020\u000a\u000d\u0009]/.test(text[index] ?? "")) index += 1; }; const bad = (): never => refuse("RATE_CATALOGUE_JSON_INVALID", "catalogue body is not closed, bounded JSON with unique keys"); const value = (depth: number): Json => { if (++nodes > 128 || depth > 8) bad(); ws(); const char = text[index]; if (char === "{") return object(depth + 1); if (char === "[") return array(depth + 1); if (char === "\"") return string(); if (text.startsWith("true", index)) { index += 4; return true; } if (text.startsWith("false", index)) { index += 5; return false; } if (text.startsWith("null", index)) { index += 4; return null; } if (char === "-" || (char !== undefined && char >= "0" && char <= "9")) return number(); return bad(); }; const object = (depth: number): JsonRecord => { index += 1; ws(); const output: Record<string, Json> = Object.create(null), keys = new Set<string>(); if (text[index] === "}") { index += 1; return output; } for (;;) { ws(); if (text[index] !== "\"") bad(); const key = string(); if (keys.has(key)) bad(); keys.add(key); ws(); if (text[index++] !== ":") bad(); output[key] = value(depth); ws(); const next = text[index++]; if (next === "}") return output; if (next !== "," || keys.size > 32) bad(); } }; const array = (depth: number): Json[] => { index += 1; ws(); const output: Json[] = []; if (text[index] === "]") { index += 1; return output; } for (;;) { output.push(value(depth)); ws(); const next = text[index++]; if (next === "]") return output; if (next !== "," || output.length > 16) bad(); } }; const string = (): string => { if (text[index++] !== "\"") bad(); let output = ""; for (;;) { const char = text[index++] ?? bad(); if (char === "\"") break; if (char === "\\") { const escape = text[index++], map: Record<string, string> = { "\"": "\"", "\\": "\\", "/": "/", b: "\b", f: "\f", n: "\n", r: "\r", t: "\t" }; if (escape === "u") { const hex = text.slice(index, index + 4); if (!/^[0-9a-fA-F]{4}$/.test(hex)) bad(); output += String.fromCharCode(Number.parseInt(hex, 16)); index += 4; } else if (escape !== undefined && escape in map) output += map[escape] ?? ""; else bad(); } else { if (char < " ") bad(); output += char; } if (output.length > 256) bad(); } return output; }; const number = (): number => { const match = text.slice(index).match(/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/); if (match === null) return bad(); index += match[0].length; const parsed = Number(match[0]); if (!Number.isFinite(parsed)) bad(); return parsed; }; const result = value(0); ws(); if (index !== text.length) bad(); return result; }
