#!/usr/bin/env node
/**
 * SELF-TEST — evidence that Arm B's guards CAN FAIL.
 *
 * CLAUDE.md, on this repository's own recurring bug:
 *
 *     "Beware the check that cannot fail. This repo has repeatedly shipped tests and gates
 *      that were structurally incapable of failing […] New gates should ship with evidence
 *      they can fail — a mutation, a negative fixture, or both."
 *
 * On the branching corpus every leak guard reports `firedTimes: 0`, and it reports that
 * HONESTLY — the corpus manifest states piping sources, carry-forward sources and
 * randomisation, so none of the three conditions arises. But "did not fire because it did
 * not apply" and "cannot fire" look identical from a single green run. This file
 * separates them.
 *
 * Two halves:
 *
 *  A. UNIT — synthetic IRs and findings that make each leak guard and each basis gate fire.
 *  B. LIVE — six synthetic HTML pages served over real HTTP and driven through a real
 *     headless Chrome, each violating exactly one declared platform assumption. This is
 *     the north-star test from CLAUDE.md applied literally: *would this still work on a
 *     survey nobody here has ever seen?* These pages are not our corpus, they are not
 *     generated by our engine, and the arm is required to NAME what it cannot handle
 *     rather than return an empty finding list.
 *
 *   node graph-spike/arm/selftest.mjs
 */

import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";

import { serve } from "../../evaluation/lib/serve.mjs";
import { launch } from "./driver.mjs";
import { preflight } from "./platform.mjs";
import { makeLeakGuards, edgeBasis, attributeBasis } from "./leaks.mjs";
import { makeMapper, classifyRoute } from "./findings.mjs";
import { alignIdentifiers } from "./entry.mjs";
import { emptyIR, validateIR } from "./ir.mjs";

const results = [];
const ok = (name, cond, detail = "") => { results.push({ name, pass: Boolean(cond), detail }); };

// ══════════════════════════════════════════════════════════ A. UNIT ══

function irWith(overrides = {}) {
  const ir = emptyIR({ ingester: "selftest", surveyId: "T" });
  Object.assign(ir, overrides);
  return ir;
}

function unitTests() {
  // ---- L1 piping ------------------------------------------------------------------
  {
    const ir = irWith({ questions: [{ id: "Q3", options: [], rules: [], __basis: { text: "stated" } }] });
    const { guards, report } = makeLeakGuards(ir);
    const g1 = guards.pipingBeforeText({ documented: "How satisfied are you with {Q2drug}?", observed: "How satisfied are you with OZEMPIC?" });
    ok("L1 downgrades when the DOCUMENT side still holds an unresolved pipe token", g1.action === "downgrade", g1.reason);
    const g2 = guards.pipingBeforeText({ documented: "How satisfied are you with OZEMPIC?", observed: "How satisfied are you with {Q2drug}?" });
    ok("L1 reclassifies to piping/raw-code-displayed when the SITE shows a literal token",
      g2.action === "reclassify" && g2.requirementClass === "piping" && g2.predicate === "raw-code-displayed", JSON.stringify(g2));
    const g3 = guards.pipingBeforeText({ documented: "A", observed: "B" });
    ok("L1 keeps an ordinary wording difference", g3.action === "keep");
    ok("L1 reports that it fired", report().find((r) => r.id === "L1").firedTimes === 2);
  }

  // ---- L2 carry-forward -------------------------------------------------------------
  {
    const ir = irWith({ questions: [{ id: "Q2", options: [], optionsFrom: { q: "Q1" } }, { id: "Q4", options: [] }] });
    const { guards, report } = makeLeakGuards(ir);
    ok("L2 downgrades 'never rendered' on a carry-forward node", guards.carryForwardAutoSkip("Q2").action === "downgrade");
    ok("L2 keeps 'never rendered' on an ordinary node", guards.carryForwardAutoSkip("Q4").action === "keep");
    ok("L2 reports that it fired", report().find((r) => r.id === "L2").firedTimes === 1);
  }

  // ---- L3 option order --------------------------------------------------------------
  {
    const ir = irWith({
      questions: [
        { id: "Q1", options: [], __basis: { optionOrder: "stated" } },
        { id: "Q2", options: [], randomize: { mode: "shuffle" }, __basis: { optionOrder: "stated" } },
        { id: "Q3", options: [], __basis: { optionOrder: "unknown" } },
      ],
    });
    const { guards, report } = makeLeakGuards(ir);
    ok("L3 keeps an order defect where the document states a fixed order", guards.optionOrderComparable("Q1").action === "keep");
    ok("L3 downgrades where the document permits randomisation", guards.optionOrderComparable("Q2").action === "downgrade");
    ok("L3 downgrades where the document says nothing about order", guards.optionOrderComparable("Q3").action === "downgrade");
    ok("L3 reports that it fired", report().find((r) => r.id === "L3").firedTimes === 2);
  }

  // ---- L4 validation/routing separation --------------------------------------------
  {
    const { guards } = makeLeakGuards(irWith({ questions: [] }));
    const clean = guards.assertValidationSeparated(new Set(["Q1|code=3"]), [{ at: "Q2", classKey: "code=1" }]);
    ok("L4 holds when no routing finding sits on an inadmissible edge", clean.ok);
    const { guards: g2 } = makeLeakGuards(irWith({ questions: [] }));
    const dirty = g2.assertValidationSeparated(new Set(["Q1|code=3"]), [{ at: "Q1", classKey: "code=3" }]);
    ok("L4 FAILS when a routing finding sits on an edge the document forbids — the assertion is not vacuous",
      dirty.ok === false && dirty.violations.length === 1, JSON.stringify(dirty.violations));
  }

  // ---- L5 resync --------------------------------------------------------------------
  {
    const { guards } = makeLeakGuards(irWith({ questions: [] }));
    const s = guards.recordResync({ findings: [1, 2, 3, 4, 5, 6, 7], resyncsUsed: 67, resyncFailures: 10 }, { findings: [1] });
    ok("L5 measures what resync recovered", s.hiddenByFirstDivergence === 6, `recovered ${s.hiddenByFirstDivergence}`);
  }

  // ---- basis gate ------------------------------------------------------------------
  {
    const ir = irWith({
      __basis: { fallThrough: "inferred", routing: "stated", questionText: "unknown", optionSet: "lower-bound" },
      questions: [{ id: "Q1", options: [], rules: [{ if: { q: "Q1", op: "eq", value: 2 }, goto: "Q5", __basis: "stated" }] }],
    });
    ok("edgeBasis: a stated rule is stated", edgeBasis(ir, "Q1", "Q5") === "stated");
    ok("edgeBasis: an unstated target is the INFERRED fall-through", edgeBasis(ir, "Q1", "Q2") === "inferred");
    ok("attributeBasis: unknown question text is unknown", attributeBasis(ir, "Q1", "text") === "unknown");
    ok("attributeBasis: a lower-bound option set is not 'stated'", attributeBasis(ir, "Q1", "options") === "lower-bound");
  }

  // ---- the basis gate actually suppresses a defect ----------------------------------
  {
    const ir = irWith({
      __basis: { fallThrough: "inferred", routing: "stated", questionText: "unknown", optionSet: "lower-bound", optionOrder: "unknown" },
      questions: [{ id: "Q1", options: [], rules: [] }],
    });
    const { guards } = makeLeakGuards(ir);
    const m = makeMapper({ ir, graphS: { nodes: {} }, guards, surveyId: "T" });
    m.fromLevelC({ findings: [{ kind: "TEXT-MISMATCH", at: "Q1", documented: null, observed: "anything" }] });
    ok("a wording comparison with no stated document text emits NO defect",
      m.findings.filter((f) => f.claimClass === "defect").length === 0);
    m.emitDowngradeObservations();
    ok("...and emits an observation instead, so it is not a silent drop",
      m.findings.some((f) => f.claimClass === "observation" && /not asserted as defects/i.test(f.prose)));
  }

  // ---- a STATED comparison still produces a defect (the gate is not a blanket mute) --
  {
    const ir = irWith({ __basis: { questionText: "stated" }, questions: [{ id: "Q1", options: [], rules: [], __basis: { text: "stated" } }] });
    const { guards } = makeLeakGuards(ir);
    const m = makeMapper({ ir, graphS: { nodes: {} }, guards, surveyId: "T" });
    m.fromLevelC({ findings: [{ kind: "TEXT-MISMATCH", at: "Q1", documented: "A", observed: "B" }] });
    ok("a wording comparison WITH stated document text does produce a defect",
      m.findings.filter((f) => f.claimClass === "defect" && f.requirementClass === "wording").length === 1);
  }

  // ---- route classification ---------------------------------------------------------
  {
    ok("terminate not triggered", classifyRoute("END:terminated", "Q5")[1] === "terminate-not-triggered");
    ok("terminate triggered unexpectedly", classifyRoute("Q5", "END:terminated")[1] === "terminate-triggered-unexpectedly");
    ok("ordinary mis-route", classifyRoute("Q5", "Q6").join("/") === "routing/route-destination-differs");
  }

  // ---- identifier alignment (DOC-01) -------------------------------------------------
  {
    const ir = irWith({ questions: [{ id: "Q1", options: [], rules: [{ if: {}, goto: "Q2" }] }, { id: "Q2", options: [] }] });
    const a = alignIdentifiers(ir, { nodes: { "q 1": {}, Q2: {} } });
    ok("alignment canonicalises a differently-spelled identifier", a.renamed.length === 1 && ir.questions[0].id === "q 1", JSON.stringify(a.renamed));
    ok("...and rewrites the rule target with it", ir.questions[0].rules[0].goto === "Q2");

    const ir2 = irWith({ questions: [{ id: "Q1", options: [] }] });
    const a2 = alignIdentifiers(ir2, { nodes: { QUESTION_ONE: {} } });
    ok("alignment reports a total namespace mismatch rather than merging", a2.matched.length === 0 && a2.overlap === 0);
  }

  // ---- IR validation is fail-closed --------------------------------------------------
  {
    ok("IR with a dangling goto is rejected",
      validateIR({ ...irWith({ questions: [{ id: "Q1", options: [], rules: [{ goto: "Q9" }] }] }) }).ok === false);
    ok("IR with a duplicate question id is rejected",
      validateIR({ ...irWith({ questions: [{ id: "Q1", options: [] }, { id: "Q1", options: [] }] }) }).ok === false);
    ok("IR with an absent option list is ACCEPTED (a numeric question has none)",
      validateIR({ ...irWith({ questions: [{ id: "Q1" }] }) }).ok === true);
  }
}

// ══════════════════════════════════════════════════════════ B. LIVE ══
/**
 * Six pages that are NOT our corpus. Each violates exactly one declared assumption. The
 * arm must name it.
 */
const FIXTURES = {
  // A perfectly ordinary web form from some other platform. The profile must not match.
  "unknown-platform.html": `<!doctype html><html><body>
    <main><form id="f"><fieldset><legend>How often do you exercise?</legend>
      <label><input type="radio" name="q1" value="1"> Daily</label>
      <label><input type="radio" name="q1" value="2"> Weekly</label>
    </fieldset><button type="submit">Continue</button></form></main></body></html>`,

  // Our shape, but the screen carries no identifier a document could name.
  "no-qid.html": `<!doctype html><html><body data-survey-status="in-progress">
    <div id="survey-root"><div class="question"><h2>How often do you exercise?</h2>
      <form class="answer-form"><label><input type="radio" name="answer" value="1"><span>Daily</span></label>
      <button class="next">Next</button></form></div></div></body></html>`,

  // Two questions on one screen: the crawler would read the first and ignore the second.
  "two-questions.html": `<!doctype html><html><body data-survey-status="in-progress">
    <div id="survey-root">
      <div class="question" data-qid="Q1"><h2>Q1. How often do you exercise?</h2>
        <form class="answer-form"><label><input type="radio" name="answer" value="1"><span>Daily</span></label></form></div>
      <div class="question" data-qid="Q2"><h2>Q2. And how would you rate it?</h2>
        <form class="answer-form"><label><input type="radio" name="q2answer" value="1"><span>Good</span></label></form></div>
      <button class="next">Next</button></div></body></html>`,

  // Forward-only is false.
  "back-button.html": `<!doctype html><html><body data-survey-status="in-progress">
    <div id="survey-root"><div class="question" data-qid="Q1"><h2>Q1. How often do you exercise?</h2>
      <form class="answer-form"><label><input type="radio" name="answer" value="1"><span>Daily</span></label></form></div>
      <button class="prev">Back</button><button class="next">Next</button></div></body></html>`,

  // A control this arm cannot drive.
  "exotic-controls.html": `<!doctype html><html><body data-survey-status="in-progress">
    <div id="survey-root"><div class="question" data-qid="Q1"><h2>Q1. Which country?</h2>
      <form class="answer-form"><select name="answer"><option value="1">UK</option><option value="2">US</option></select>
      <input type="range" name="slider" min="0" max="10">
      <button class="next">Next</button></form></div></div></body></html>`,

  // Content that has not finished arriving when the first observation happens.
  "late-render.html": `<!doctype html><html><body data-survey-status="in-progress">
    <div id="survey-root"><div class="question" data-qid="Q1"><h2>Q1. Loading…</h2>
      <form class="answer-form"><label><input type="radio" name="answer" value="1"><span>One</span></label>
      <button class="next">Next</button></form></div></div>
    <script>
      let n = 0;
      const t = setInterval(() => {
        const d = document.createElement("p"); d.textContent = "late " + (++n);
        document.getElementById("survey-root").appendChild(d);
        if (n > 40) clearInterval(t);
      }, 40);
    </script></body></html>`,
};

function browserFor(driver) {
  const visits = [];
  const b = {
    available: true,
    visits,
    async goto(u) { await driver.goto(u); await b.observe(); },
    async observe() {
      const s = await driver.evaluate(function () {
        const el = document.querySelector("[data-qid]");
        return { qid: el ? el.getAttribute("data-qid") : null };
      });
      if (s?.qid) visits.push(s.qid);
      return s;
    },
    async act(fn) { const r = await driver.evaluate(fn); await b.observe(); return r; },
    async close() {},
  };
  return b;
}

async function liveTests() {
  const dir = join(tmpdir(), `arm-b-selftest-${Date.now().toString(36)}`);
  mkdirSync(dir, { recursive: true });
  for (const [name, html] of Object.entries(FIXTURES)) writeFileSync(join(dir, name), html);

  const server = await serve(dir, 0);
  const driver = await launch();
  const { makePageBridge } = await import("./page-bridge.mjs");

  const run = async (file) => {
    const page = makePageBridge(browserFor(driver), {});
    try {
      return await preflight(page, `${server.base}/${file}`, { settleMs: 400 });
    } catch (e) {
      return { threw: e.message, ok: false, checks: [], blockers: [], limitations: [] };
    }
  };
  const verdictOf = (pf, id) => pf.checks.find((c) => c.id === id)?.verdict;

  try {
    const unknown = await run("unknown-platform.html");
    ok("LIVE unknown platform: the arm refuses to proceed", unknown.ok === false, unknown.threw || "");
    ok("LIVE unknown platform: it NAMES the selectors that did not match",
      unknown.checks.some((c) => /platform profile .* does not match/.test(c.detail || "")),
      unknown.checks.map((c) => c.detail).join(" | ").slice(0, 200));

    const noQid = await run("no-qid.html");
    ok("LIVE no question id: SITE-01 is violated", verdictOf(noQid, "SITE-01") === "violated");
    ok("LIVE no question id: the arm refuses to proceed", noQid.ok === false);

    const two = await run("two-questions.html");
    ok("LIVE two questions on one screen: SITE-02 is violated", verdictOf(two, "SITE-02") === "violated");
    ok("LIVE two questions on one screen: the arm refuses to proceed", two.ok === false);

    const back = await run("back-button.html");
    ok("LIVE back button: SITE-03 is violated", verdictOf(back, "SITE-03") === "violated");
    ok("LIVE back button: it is a LIMITATION, not a stop — the arm still proceeds",
      back.ok === true && back.limitations.some((l) => l.id === "SITE-03"));

    const exotic = await run("exotic-controls.html");
    ok("LIVE unrecognised control: SITE-04 is violated", verdictOf(exotic, "SITE-04") === "violated");
    ok("LIVE unrecognised control: it is a limitation, not a stop", exotic.ok === true);

    const late = await run("late-render.html");
    ok("LIVE late render: SITE-05 is violated", verdictOf(late, "SITE-05") === "violated");

    // The two that can never fail a check are reported EVERY run, on every page.
    for (const [label, pf] of [["back-button", back], ["exotic", exotic]]) {
      ok(`LIVE ${label}: the undetectable assumptions are still reported`,
        verdictOf(pf, "SITE-06") === "undetectable" && verdictOf(pf, "SITE-07") === "undetectable");
    }

    // Blinding: the fixtures carry no oracle, and the guard must say so rather than throw.
    ok("LIVE blinding guard runs clean on a page with no inline oracle", back.blinding?.clean === true);

    // ---- END TO END on a survey nobody here has ever seen ---------------------------
    // The whole arm, not just the pre-flight. What must NOT come back is an empty finding
    // list, because an empty finding list reads as a clean bill of health.
    const { runArmB } = await import("./entry.mjs");
    const { validateArmResult, FINDING_SCHEMA_VERSION } = await import("../../evaluation/finding-schema.mjs");
    const armDefault = (await import("../../evaluation/adapters/b.mjs")).default;
    const e2e = await runArmB(
      {
        surveyId: "unknown-platform", arm: "B", baseUrl: server.base,
        docxPath: join(dir, "unknown-platform.html"), // never read: the arm stops before ingestion
        browser: browserFor(driver), model: null, budget: { caps: {}, check: () => {} }, log: () => {},
      },
      { ingester: "manifest", entryPath: "/unknown-platform.html" },
    );
    ok("E2E on an unrecognised platform: at least one BLOCKER, and zero defect assertions",
      e2e.findings.some((f) => f.claimClass === "blocker") && !e2e.findings.some((f) => f.claimClass === "defect"),
      JSON.stringify(e2e.findings.map((f) => f.claimClass)));
    ok("E2E on an unrecognised platform: it does NOT return an empty finding list", e2e.findings.length > 0);
    ok("E2E on an unrecognised platform: every coverage unit is blocked/not-assessed",
      e2e.claimedUnits.length > 0 && e2e.claimedUnits.every((u) => u.verdict === "not-assessed"),
      JSON.stringify(e2e.claimedUnits));
    ok("E2E on an unrecognised platform: judgement is still model-free", e2e.selfReportedCost.judgementIsModelFree === true);
    const v = validateArmResult({
      schemaVersion: FINDING_SCHEMA_VERSION, arm: "B", armVersion: "selftest",
      armIdentity: armDefault.identity(), surveyId: "unknown-platform", seed: null,
      findings: e2e.findings, coverage: { claimedUnits: e2e.claimedUnits }, selfReportedCost: e2e.selfReportedCost,
    });
    ok("E2E blocked output still validates against the harness schema", v.ok, JSON.stringify(v.errors).slice(0, 300));
  } finally {
    await driver.close().catch(() => {});
    await server.close();
    rmSync(dir, { recursive: true, force: true });
  }
}

// ══════════════════════════════════════════════════ C. LEDGER -> GRAPH-D ══
/**
 * The deliverable the branching corpus CANNOT exercise: Graph-D compiled from the shared
 * extraction's requirement ledger rather than from a manifest.
 *
 * This drives the REAL `mergePasses` and `expandFloor` out of `worker-v2/src/extract`,
 * with only the two model HTTP calls replaced by hand-written `PassResult`s in the exact
 * shape `coerceRequirement` produces. So everything downstream of the model — the merge,
 * the lineage ids, the expansion into typed route cases, and Arm B's compiler — is the
 * real code path. What is NOT proved here is that Grok and DeepSeek emit these shapes on a
 * real questionnaire; that needs the credentials, and this file does not pretend otherwise.
 */
async function ledgerTests() {
  const { loadSharedExtraction } = await import("./extract-bridge.mjs");
  const { compileIRFromLedger } = await import("./ingest.mjs");
  const { completeness } = await import("./ir.mjs");
  const { module: X } = await loadSharedExtraction();

  const blocks = ["S1", "Q1", "Q2", "Q3", "Q4", "Q5"].flatMap((q, i) => [
    { blockId: `b000${i + 1}`, kind: "paragraph", text: `${q}. A question about something.`, origin: "body", section: "MAIN", coords: null, tableId: null },
  ]);
  const doc = {
    blocks,
    coverage: { archiveParts: 3, partsRead: ["word/document.xml"], partsSkipped: [], images: 0, imagesWithAltText: 0, unresolvedFieldCodes: 0, symbolRuns: 0, autoNumberedParagraphs: 0, problems: [] },
  };

  const req = (o) => ({
    id: o.id, construct: o.construct, scope: o.scope, quantifier: "specific", selector: null, exceptions: [],
    statement: o.statement, docQuote: o.statement, blockIds: o.blockIds, browserObservable: "full",
    confidence: 0.9, expansion: o.expansion ?? null, pass: o.pass ?? "B", origin: o.origin ?? "C01-b0001",
  });

  const passB = {
    pass: "B", provider: "deepseek", model: "deepseek-v4-pro",
    requirements: [
      // 1. a clean, fully typed skip rule
      req({ id: "OBL-1", construct: "skip-rule", scope: "question:Q2", blockIds: ["b0003"],
        statement: "If Q2 = 2 (No), skip to Q5.",
        expansion: { kind: "route", routeAnswers: [{ code: "2", label: "No", destination: "Q5" }], maxLength: null, minSelections: null, maxSelections: null } }),
      // 2. a terminate, recognised only through destinationOf()'s keyword regex
      req({ id: "OBL-2", construct: "terminate", scope: "question:S1", blockIds: ["b0001"],
        statement: "Terminate if S1 = 4.",
        expansion: { kind: "route", routeAnswers: [{ code: "4", label: "Other", destination: "screenout" }], maxLength: null, minSelections: null, maxSelections: null } }),
      // 3. a route whose trigger has a label but NO code — not constructible as an answer class
      req({ id: "OBL-3", construct: "skip-rule", scope: "question:Q3", blockIds: ["b0004"],
        statement: "If the respondent prescribes nothing, skip ahead.",
        expansion: { kind: "route", routeAnswers: [{ code: null, label: "prescribes nothing", destination: "Q5" }], maxLength: null, minSelections: null, maxSelections: null } }),
      // 4. a route whose destination is prose
      req({ id: "OBL-4", construct: "skip-rule", scope: "question:Q4", blockIds: ["b0005"],
        statement: "If Q4 = 1, go to the next section.",
        expansion: { kind: "route", routeAnswers: [{ code: "1", label: "Yes", destination: "the next section" }], maxLength: null, minSelections: null, maxSelections: null } }),
      // 5. a routing rule stated only in prose — the commonest real case
      req({ id: "OBL-5", construct: "skip-rule", scope: "question:Q1", blockIds: ["b0002"],
        statement: "Respondents managing fewer than 5 patients per month do not see Q3.", expansion: null }),
      // 6. a node attribute the graph has no field for
      req({ id: "OBL-6", construct: "option-list", scope: "question:Q3", blockIds: ["b0004"],
        statement: "Q3 offers exactly five brands.", expansion: null }),
      // 7. Q5 exists. This is what puts Q5 in the expander's question VOCABULARY, which is
      //    the only way rule 1's destination can bind — `expand.ts#bindDestination` refuses
      //    to invent a destination the document never names.
      req({ id: "OBL-7", construct: "question", scope: "question:Q5", blockIds: ["b0006"],
        statement: "Q5 asks about barriers to use.", expansion: null }),
    ],
    ambiguities: [], unverifiable: [], dispositions: blocks.map((b) => ({ blockId: b.blockId, disposition: "normative", reason: "carries a rule" })),
    constructs: [], failedUnits: [], calls: [],
  };
  const passA = { pass: "A", provider: "grok", model: "grok-4.5", requirements: [], ambiguities: [], unverifiable: [], dispositions: [], constructs: [], failedUnits: [], calls: [] };

  const merged = await X.mergePasses(passA, passB, doc, []);
  const expansion = await X.expandFloor(merged.rows, { locale: "en", viewport: null });
  ok("REAL mergePasses produced a ledger row per obligation", merged.rows.length === 7, `${merged.rows.length} rows`);
  ok("REAL expandFloor produced typed route cases", expansion.facetInstances.some((f) => f.case?.kind === "route"),
    `${expansion.facetInstances.length} facet instances`);

  const ir = compileIRFromLedger({ surveyId: "T", provenance: { ingester: "shared-extract" }, merged, expansion, doc });
  const v = validateIR(ir);
  ok("Graph-D compiled from the ledger VALIDATES", v.ok, JSON.stringify(v.errors));

  const byId = Object.fromEntries(ir.questions.map((q) => [q.id, q]));
  ok("the typed skip rule became an edge Q2 --code 2--> Q5",
    (byId.Q2?.rules || []).some((r) => r.goto === "Q5" && r.if?.value === 2), JSON.stringify(byId.Q2?.rules));
  ok("the screenout destination became a terminate at S1",
    (byId.S1?.rules || []).some((r) => r.terminate), JSON.stringify(byId.S1?.rules));
  ok("a destination named only in the document's own prose became a NODE",
    Boolean(byId.Q5), Object.keys(byId).join(","));
  ok("the route-triggering option code was recorded as a LOWER-BOUND option list",
    (byId.Q2?.options || []).some((o) => o.code === 2), JSON.stringify(byId.Q2?.options));

  const comp = completeness(ir);
  ok("a route trigger with no numeric code is UNRESOLVED, not guessed",
    comp.unresolvedByCode.ROUTE_ANSWER_NOT_A_CODE === 1, JSON.stringify(comp.unresolvedByCode));
  ok("a prose destination is UNRESOLVED under the SHARED expander's own gap code, not re-reasoned here",
    comp.unresolvedByCode.ROUTE_DESTINATION_NOT_BOUND === 1, JSON.stringify(comp.unresolvedByCode));
  ok("a terminal destination compiles BUT carries the expander's caveat that terminals are not discriminable",
    comp.caveatsByCode.ROUTE_DESTINATION_TERMINAL === 1, JSON.stringify(comp.caveatsByCode));
  // A routing rule the models read as prose and never enumerated. The shared expander
  // classes it `ROUTE_ANSWERS_NOT_ENUMERATED`; Arm B carries that code through rather
  // than substituting its own, so this arm and `verify-observations.ts` name the same
  // condition the same way.
  ok("a routing rule with no typed expansion is UNRESOLVED and counted",
    (comp.unresolvedByCode.ROUTE_ANSWERS_NOT_ENUMERATED ?? comp.unresolvedByCode.ROUTE_WITHOUT_EXPANSION ?? 0) >= 1,
    JSON.stringify(comp.unresolvedByCode));
  ok("a node-attribute requirement is counted as not-graph-shaped rather than dropped",
    comp.unresolvedByCode.CONSTRUCT_NOT_GRAPH_SHAPED >= 1, JSON.stringify(comp.unresolvedByCode));
  ok("the compiled share is REPORTED and is well under 1 — the honest number for a real document",
    comp.compiledShare !== null && comp.compiledShare < 1, `compiledShare=${comp.compiledShare?.toFixed(2)} (${comp.requirementsCompiled}/${comp.requirementsIn})`);

  ok("basis: fall-through is INFERRED, because the extraction schema has no field for it", ir.__basis.fallThrough === "inferred");
  ok("basis: question text is UNKNOWN, so wording is never compared", ir.__basis.questionText === "unknown");
  ok("basis: the option set is a LOWER BOUND, so 'undocumented option' is never asserted", ir.__basis.optionSet === "lower-bound");
  ok("every compiled node carries type 'unknown' — no input type is invented",
    ir.questions.every((q) => q.type === "unknown"));
}

// ═══════════════════════════════════════════════════════════════════════════

unitTests();
await ledgerTests();
await liveTests();

const failed = results.filter((r) => !r.pass);
for (const r of results) console.log(`${r.pass ? "  ok  " : "  FAIL"}  ${r.name}${r.pass ? "" : `\n         ${r.detail}`}`);
console.log(`\n${results.length - failed.length}/${results.length} passed`);
process.exit(failed.length ? 1 : 0);
