// gen-pages.mjs — generates the live survey pages for the BRANCHING corpus.
//
// For each survey dir: manifest.json -> index.html (clean),
// manifest.flawed.json -> flawed.html. The manifest is inlined as
// <script type="application/json" id="survey-manifest"> so every page is a
// fully self-contained static file (opens from file:// with zero network).
// validate.mjs re-asserts that the inlined JSON still matches the manifest
// file, so regenerate after any manifest edit:
//
//   node test-suite/branching/gen-pages.mjs
//
// LEAK CONTROL: the flawed page must be indistinguishable from the clean one
// to the tool under test, so the inlined payload strips the answer key
// (variant, basedOn, seededErrors, notes) from BOTH variants and both pages
// share the clean <title>.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const SLUGS = [
  "s1-skip",
  "s2-screener",
  "s3-multiselect-piping",
  "s4-nested-rotation",
  "s5-allocation",
  "s6-kitchen-sink",
];

export function stripAnswerKey(manifest) {
  const core = structuredClone(manifest);
  delete core.variant;
  delete core.basedOn;
  delete core.seededErrors;
  delete core.notes;
  return core;
}

const CSS = `
    body { margin: 0; background: #f3f3f3; font-family: "Segoe UI", Arial, sans-serif; color: #1a1a1a; }
    #survey-root { max-width: 720px; margin: 0 auto; padding: 2em 1.5em 4em; }
    .intro h1, .question h2 { font-size: 1.25em; line-height: 1.4; }
    .instruction { font-style: italic; color: #555; }
    .opt, .rate { display: block; padding: 0.4em 0.2em; cursor: pointer; }
    .rating-row { display: flex; flex-wrap: wrap; gap: 0.25em; }
    .rating-row .rate { display: inline-flex; flex-direction: column; align-items: center; padding: 0.3em 0.5em; }
    input[type="number"], textarea { font: inherit; padding: 0.4em; width: 100%; max-width: 20em; box-sizing: border-box; }
    table.alloc { border-collapse: collapse; margin: 1em 0; }
    table.alloc td { border: 1px solid #ccc; padding: 0.4em 0.7em; }
    table.alloc input { width: 6em; }
    tr.alloc-total td { font-weight: bold; background: #fafafa; }
    .errors p { color: #c0392b; margin: 0.35em 0; }
    button.next { margin-top: 1.25em; padding: 0.55em 1.6em; font: inherit; background: #19b394; color: #fff; border: 0; border-radius: 3px; cursor: pointer; }
    button.next:hover { background: #14856e; }
    .end-screen { text-align: center; padding-top: 3em; }
`;

function page(title, manifestJson) {
  // "</" inside the inlined JSON would close the <script> tag early; JSON
  // strings may legally escape "/" so "<\\/" round-trips via JSON.parse.
  const safeJson = manifestJson.replace(/<\//g, "<\\/");
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <style>${CSS}</style>
</head>
<body>
  <!-- GENERATED by gen-pages.mjs — edit the manifest, then regenerate. -->
  <div id="survey-root"></div>
  <script type="application/json" id="survey-manifest">
${safeJson}
  </script>
  <script src="../engine.js"></script>
  <script>SurveyEngine.initBrowser();</script>
</body>
</html>
`;
}

// Only run the generator when executed directly (validate.mjs imports
// stripAnswerKey from this module without wanting a rebuild).
if (process.argv[1] && import.meta.url === new URL(`file:///${process.argv[1].replace(/\\/g, "/")}`).href) {
  for (const slug of SLUGS) {
    const clean = JSON.parse(readFileSync(join(root, slug, "manifest.json"), "utf8"));
    const flawed = JSON.parse(readFileSync(join(root, slug, "manifest.flawed.json"), "utf8"));
    const title = clean.title; // shared title: the flawed page must not out itself
    writeFileSync(
      join(root, slug, "index.html"),
      page(title, JSON.stringify(stripAnswerKey(clean), null, 2))
    );
    writeFileSync(
      join(root, slug, "flawed.html"),
      page(title, JSON.stringify(stripAnswerKey(flawed), null, 2))
    );
    console.log(`Wrote ${slug}/index.html + ${slug}/flawed.html`);
  }
}
